declare module 'lucide-react' {
  import { ComponentType, SVGAttributes } from 'react'

  interface IconProps extends SVGAttributes<SVGElement> {
    size?: number | string
    color?: string
    strokeWidth?: number | string
  }

  export const MessageSquare: ComponentType<IconProps>
  export const Plus: ComponentType<IconProps>
  export const Heart: ComponentType<IconProps>
  export const MessageCircle: ComponentType<IconProps>
  export const Share2: ComponentType<IconProps>
  export const Bookmark: ComponentType<IconProps>
  export const MoreHorizontal: ComponentType<IconProps>
  export const Home: ComponentType<IconProps>
  export const Users: ComponentType<IconProps>
  export const Briefcase: ComponentType<IconProps>
  export const Building: ComponentType<IconProps>
  export const Calendar: ComponentType<IconProps>
  export const Bell: ComponentType<IconProps>
  export const User: ComponentType<IconProps>
  export const Search: ComponentType<IconProps>
  export const Settings: ComponentType<IconProps>
  export const LogOut: ComponentType<IconProps>
  export const Menu: ComponentType<IconProps>
  export const X: ComponentType<IconProps>
  export const ChevronDown: ComponentType<IconProps>
  export const ChevronUp: ComponentType<IconProps>
  export const ChevronLeft: ComponentType<IconProps>
  export const ChevronRight: ComponentType<IconProps>
  export const Edit: ComponentType<IconProps>
  export const Trash2: ComponentType<IconProps>
  export const Save: ComponentType<IconProps>
  export const Camera: ComponentType<IconProps>
  export const MapPin: ComponentType<IconProps>
  export const Link: ComponentType<IconProps>
  export const Globe: ComponentType<IconProps>
  export const Mail: ComponentType<IconProps>
  export const Phone: ComponentType<IconProps>
  export const Award: ComponentType<IconProps>
  export const BookOpen: ComponentType<IconProps>
  export const GraduationCap: ComponentType<IconProps>
  export const Star: ComponentType<IconProps>
  export const TrendingUp: ComponentType<IconProps>
  export const Eye: ComponentType<IconProps>
  export const EyeOff: ComponentType<IconProps>
  export const Check: ComponentType<IconProps>
  export const CheckCircle: ComponentType<IconProps>
  export const XCircle: ComponentType<IconProps>
  export const AlertCircle: ComponentType<IconProps>
  export const Info: ComponentType<IconProps>
  export const Loader: ComponentType<IconProps>
  export const Loader2: ComponentType<IconProps>
  export const ArrowLeft: ComponentType<IconProps>
  export const ArrowRight: ComponentType<IconProps>
  export const ArrowUp: ComponentType<IconProps>
  export const ArrowDown: ComponentType<IconProps>
  export const ExternalLink: ComponentType<IconProps>
  export const Image: ComponentType<IconProps>
  export const Send: ComponentType<IconProps>
  export const Paperclip: ComponentType<IconProps>
  export const ThumbsUp: ComponentType<IconProps>
  export const ThumbsDown: ComponentType<IconProps>
  export const Flag: ComponentType<IconProps>
  export const Filter: ComponentType<IconProps>
  export const Grid: ComponentType<IconProps>
  export const List: ComponentType<IconProps>
  export const Layout: ComponentType<IconProps>
  export const Zap: ComponentType<IconProps>
  export const Clock: ComponentType<IconProps>
  export const Lock: ComponentType<IconProps>
  export const Unlock: ComponentType<IconProps>
  export const Shield: ComponentType<IconProps>
  export const Key: ComponentType<IconProps>
  export const FileText: ComponentType<IconProps>
  export const File: ComponentType<IconProps>
  export const Folder: ComponentType<IconProps>
  export const FolderOpen: ComponentType<IconProps>
  export const Download: ComponentType<IconProps>
  export const Upload: ComponentType<IconProps>
  export const Copy: ComponentType<IconProps>
  export const Clipboard: ComponentType<IconProps>
  export const Scissors: ComponentType<IconProps>
  export const Tag: ComponentType<IconProps>
  export const Tags: ComponentType<IconProps>
  export const Hash: ComponentType<IconProps>
  export const AtSign: ComponentType<IconProps>
  export const Map: ComponentType<IconProps>
  export const Navigation: ComponentType<IconProps>
  export const Compass: ComponentType<IconProps>
  export const Anchor: ComponentType<IconProps>
  export const LifeBuoy: ComponentType<IconProps>
  export const HelpCircle: ComponentType<IconProps>
  export const Moon: ComponentType<IconProps>
  export const Sun: ComponentType<IconProps>
  export const Cloud: ComponentType<IconProps>
  export const CloudRain: ComponentType<IconProps>
  export const CloudSnow: ComponentType<IconProps>
  export const Wind: ComponentType<IconProps>
  export const Thermometer: ComponentType<IconProps>
  export const Droplet: ComponentType<IconProps>
  export const Flame: ComponentType<IconProps>
  export const Coffee: ComponentType<IconProps>
  export const Gift: ComponentType<IconProps>
  export const PartyPopper: ComponentType<IconProps>
  export const Sparkles: ComponentType<IconProps>
  export const Wand: ComponentType<IconProps>
  export const Palette: ComponentType<IconProps>
  export const Brush: ComponentType<IconProps>
  export const Pen: ComponentType<IconProps>
  export const Pencil: ComponentType<IconProps>
  export const Highlighter: ComponentType<IconProps>
  export const Eraser: ComponentType<IconProps>
  export const Ruler: ComponentType<IconProps>
  export const CompassDrafting: ComponentType<IconProps>
  export const Printer: ComponentType<IconProps>
  export const Monitor: ComponentType<IconProps>
  export const Smartphone: ComponentType<IconProps>
  export const Tablet: ComponentType<IconProps>
  export const Watch: ComponentType<IconProps>
  export const Headphones: ComponentType<IconProps>
  export const Mic: ComponentType<IconProps>
  export const Volume: ComponentType<IconProps>
  export const Volume1: ComponentType<IconProps>
  export const Volume2: ComponentType<IconProps>
  export const VolumeX: ComponentType<IconProps>
  export const Play: ComponentType<IconProps>
  export const Pause: ComponentType<IconProps>
  export const StopCircle: ComponentType<IconProps>
  export const SkipBack: ComponentType<IconProps>
  export const SkipForward: ComponentType<IconProps>
  export const Repeat: ComponentType<IconProps>
  export const Shuffle: ComponentType<IconProps>
  export const Music: ComponentType<IconProps>
  export const Radio: ComponentType<IconProps>
  export const Podcast: ComponentType<IconProps>
  export const Video: ComponentType<IconProps>
  export const Film: ComponentType<IconProps>
  export const Tv: ComponentType<IconProps>
  export const Cast: ComponentType<IconProps>
  export const Maximize: ComponentType<IconProps>
  export const Minimize: ComponentType<IconProps>
  export const Expand: ComponentType<IconProps>
  export const Shrink: ComponentType<IconProps>
  export const Move: ComponentType<IconProps>
  export const RotateCw: ComponentType<IconProps>
  export const RotateCcw: ComponentType<IconProps>
  export const RefreshCw: ComponentType<IconProps>
  export const RefreshCcw: ComponentType<IconProps>
  export const Power: ComponentType<IconProps>
  export const Plug: ComponentType<IconProps>
  export const Battery: ComponentType<IconProps>
  export const BatteryCharging: ComponentType<IconProps>
  export const Wifi: ComponentType<IconProps>
  export const WifiOff: ComponentType<IconProps>
  export const Bluetooth: ComponentType<IconProps>
  export const Signal: ComponentType<IconProps>
  export const Activity: ComponentType<IconProps>
  export const Cpu: ComponentType<IconProps>
  export const HardDrive: ComponentType<IconProps>
  export const Server: ComponentType<IconProps>
  export const Database: ComponentType<IconProps>
  export const Terminal: ComponentType<IconProps>
  export const Code: ComponentType<IconProps>
  export const Code2: ComponentType<IconProps>
  export const GitBranch: ComponentType<IconProps>
  export const GitCommit: ComponentType<IconProps>
  export const GitMerge: ComponentType<IconProps>
  export const GitPullRequest: ComponentType<IconProps>
  export const Github: ComponentType<IconProps>
  export const Gitlab: ComponentType<IconProps>
  export const Twitter: ComponentType<IconProps>
  export const Facebook: ComponentType<IconProps>
  export const Instagram: ComponentType<IconProps>
  export const Linkedin: ComponentType<IconProps>
  export const Youtube: ComponentType<IconProps>
  export const Slack: ComponentType<IconProps>
  export const Discord: ComponentType<IconProps>
  export const Twitch: ComponentType<IconProps>
  export const Dribbble: ComponentType<IconProps>
  export const Behance: ComponentType<IconProps>
  export const Figma: ComponentType<IconProps>
  export const Chrome: ComponentType<IconProps>
  export const Safari: ComponentType<IconProps>
  export const Firefox: ComponentType<IconProps>
  export const Edge: ComponentType<IconProps>
  export const Apple: ComponentType<IconProps>
  export const Android: ComponentType<IconProps>
  export const Windows: ComponentType<IconProps>
  export const Command: ComponentType<IconProps>
  export const Shift: ComponentType<IconProps>
  export const Alt: ComponentType<IconProps>
  export const Control: ComponentType<IconProps>
  export const Option: ComponentType<IconProps>
  export const Backspace: ComponentType<IconProps>
  export const Enter: ComponentType<IconProps>
  export const Tab: ComponentType<IconProps>
  export const CapsLock: ComponentType<IconProps>
  export const ArrowUpLeft: ComponentType<IconProps>
  export const ArrowUpRight: ComponentType<IconProps>
  export const ArrowDownLeft: ComponentType<IconProps>
  export const ArrowDownRight: ComponentType<IconProps>
  export const CornerUpLeft: ComponentType<IconProps>
  export const CornerUpRight: ComponentType<IconProps>
  export const CornerDownLeft: ComponentType<IconProps>
  export const CornerDownRight: ComponentType<IconProps>
  export const CornerLeftUp: ComponentType<IconProps>
  export const CornerLeftDown: ComponentType<IconProps>
  export const CornerRightUp: ComponentType<IconProps>
  export const CornerRightDown: ComponentType<IconProps>
  export const MousePointer: ComponentType<IconProps>
  export const MousePointer2: ComponentType<IconProps>
  export const MousePointerClick: ComponentType<IconProps>
  export const Hand: ComponentType<IconProps>
  export const Grab: ComponentType<IconProps>
  export const Crosshair: ComponentType<IconProps>
  export const Target: ComponentType<IconProps>
  export const Circle: ComponentType<IconProps>
  export const Square: ComponentType<IconProps>
  export const Triangle: ComponentType<IconProps>
  export const Hexagon: ComponentType<IconProps>
  export const Octagon: ComponentType<IconProps>
  export const Pentagon: ComponentType<IconProps>
  export const Diamond: ComponentType<IconProps>
  export const Box: ComponentType<IconProps>
  export const Package: ComponentType<IconProps>
  export const Archive: ComponentType<IconProps>
  export const Inbox: ComponentType<IconProps>
  export const Trash: ComponentType<IconProps>
  export const Recycle: ComponentType<IconProps>
  export const ShoppingBag: ComponentType<IconProps>
  export const ShoppingCart: ComponentType<IconProps>
  export const CreditCard: ComponentType<IconProps>
  export const DollarSign: ComponentType<IconProps>
  export const Euro: ComponentType<IconProps>
  export const PoundSterling: ComponentType<IconProps>
  export const Yen: ComponentType<IconProps>
  export const Bitcoin: ComponentType<IconProps>
  export const Percent: ComponentType<IconProps>
  export const PieChart: ComponentType<IconProps>
  export const BarChart: ComponentType<IconProps>
  export const BarChart2: ComponentType<IconProps>
  export const BarChart3: ComponentType<IconProps>
  export const BarChart4: ComponentType<IconProps>
  export const LineChart: ComponentType<IconProps>
  export const AreaChart: ComponentType<IconProps>
  export const ScatterChart: ComponentType<IconProps>
  export const TrendingDown: ComponentType<IconProps>
  export const Activity2: ComponentType<IconProps>
  export const Pulse: ComponentType<IconProps>
  export const HeartPulse: ComponentType<IconProps>
  export const Stethoscope: ComponentType<IconProps>
  export const Pill: ComponentType<IconProps>
  export const Syringe: ComponentType<IconProps>
  export const ThermometerSun: ComponentType<IconProps>
  export const ThermometerSnowflake: ComponentType<IconProps>
  export const Brain: ComponentType<IconProps>
  export const Eye2: ComponentType<IconProps>
  export const Ear: ComponentType<IconProps>
  export const HandMetal: ComponentType<IconProps>
  export const Footprints: ComponentType<IconProps>
  export const Baby: ComponentType<IconProps>
  export const UserPlus: ComponentType<IconProps>
  export const UserMinus: ComponentType<IconProps>
  export const UserCheck: ComponentType<IconProps>
  export const UserX: ComponentType<IconProps>
  export const Users2: ComponentType<IconProps>
  export const UsersRound: ComponentType<IconProps>
  export const CircleUser: ComponentType<IconProps>
  export const SquareUser: ComponentType<IconProps>
  export const UserCircle: ComponentType<IconProps>
  export const UserSquare: ComponentType<IconProps>
  export const Smile: ComponentType<IconProps>
  export const Frown: ComponentType<IconProps>
  export const Meh: ComponentType<IconProps>
  export const Angry: ComponentType<IconProps>
  export const Laugh: ComponentType<IconProps>
  export const Grimace: ComponentType<IconProps>
  export const Wink: ComponentType<IconProps>
  export const ThumbsUp2: ComponentType<IconProps>
  export const ThumbsDown2: ComponentType<IconProps>
  export const Clap: ComponentType<IconProps>
  export const Wave: ComponentType<IconProps>
  export const Peace: ComponentType<IconProps>
  export const Rock: ComponentType<IconProps>
  export const Scissors2: ComponentType<IconProps>
  export const Paper: ComponentType<IconProps>
  export const Document: ComponentType<IconProps>
  export const FileCode: ComponentType<IconProps>
  export const FileJson: ComponentType<IconProps>
  export const FileImage: ComponentType<IconProps>
  export const FileVideo: ComponentType<IconProps>
  export const FileAudio: ComponentType<IconProps>
  export const FileArchive: ComponentType<IconProps>
  export const FileSpreadsheet: ComponentType<IconProps>
  export const FilePresentation: ComponentType<IconProps>
  export const Newspaper: ComponentType<IconProps>
  export const Book: ComponentType<IconProps>
  export const Book2: ComponentType<IconProps>
  export const Library: ComponentType<IconProps>
  export const Bookmark2: ComponentType<IconProps>
  export const BookMarked: ComponentType<IconProps>
  export const BookOpen2: ComponentType<IconProps>
  export const BookOpenCheck: ComponentType<IconProps>
  export const BookOpenText: ComponentType<IconProps>
  export const BookCopy: ComponentType<IconProps>
  export const BookPlus: ComponentType<IconProps>
  export const BookMinus: ComponentType<IconProps>
  export const BookX: ComponentType<IconProps>
  export const BookCheck: ComponentType<IconProps>
  export const BookHeart: ComponentType<IconProps>
  export const BookImage: ComponentType<IconProps>
  export const BookKey: ComponentType<IconProps>
  export const BookLock: ComponentType<IconProps>
  export const BookType: ComponentType<IconProps>
  export const BookUser: ComponentType<IconProps>
  export const BookWorm: ComponentType<IconProps>
}
